<P align="center"><b>
<a href="main2.php?nome=A"> A </a> -
<a href="main2.php?nome=B"> B </a> -
<a href="main2.php?nome=C"> C </a> -
<a href="main2.php?nome=D"> D </a> -
<a href="main2.php?nome=E"> E </a> -
<a href="main2.php?nome=F"> F </a> -
<a href="main2.php?nome=G"> G </a> -
<a href="main2.php?nome=H"> H </a> -
<a href="main2.php?nome=I"> I </a> -
<a href="main2.php?nome=J"> J </a> -
<a href="main2.php?nome=K"> K </a> -
<a href="main2.php?nome=L"> L </a> -
<a href="main2.php?nome=M"> M </a> -
<a href="main2.php?nome=N"> N </a> -
<a href="main2.php?nome=O"> O </a> -
<a href="main2.php?nome=P"> P </a> -
<a href="main2.php?nome=Q"> Q </a> -
<a href="main2.php?nome=R"> R </a> -
<a href="main2.php?nome=S"> S </a> -
<a href="main2.php?nome=T"> T </a> -
<a href="main2.php?nome=U"> U </a> -
<a href="main2.php?nome=V"> V </a> -
<a href="main2.php?nome=X"> X </a> -
<a href="main2.php?nome=Z"> Z </a> -
<a href="main2.php?nome=%"> * </a> -
<P><hr>